#!/bin/bash

# File that contains the API response
JSON_FILE="sdata.json"

# Check if file exists
if [ ! -f "$JSON_FILE" ]; then
    echo "Error: $JSON_FILE not found."
    exit 1
fi

# Extract fields using jq
NAME=$(jq -r '.name' "$JSON_FILE" | sed 's/.*/\u&/') 
height=$(jq -r '.height' data.json)
weight=$(jq -r '.weight' data.json)
type=$(jq -r '.types[].type.name' data.json | sed 's/.*/\u&/' | paste -sd ', ' -)

formatted_height=$(awk "BEGIN { printf \"%.1f\", $height / 10 }")
formatted_weight=$(awk "BEGIN { printf \"%.0f\", $weight / 10 }")


# Output formatted string
echo "$name is of type $type, weighs ${formatted_weight}kg, and is ${formatted_height}m tall."

